### ISSUE TITLE
Замечания по документации

### ISSUE THREAD

**Issue by sedx** [TheRole/docs#1]
@the-teacher  Посмотрел документцию.
1. Не понятно про Иморт и Экспорт ролей. Просто описано в общих чертах, а как это сделать не описано. Тут, как мне кажется, важно указать что этот функционал представляется в ManagmentPanel
2. Не нашел упомаинания про то как работать с механизмом вледения секцией, только про то как узнать является ли пользователь владельцем. И еще тут важно что у объекта @page `@user.owner?(@page)` должно быть поле user_id. Тоже касается и описании использования :owner_required в доке по интеграции с контроллерами. Может стоит вынести в отдельный пункт в докуе по установке? Суть пункта будет в том, что если предполагается использовать методы `#owner?` и фильтр `owner_required` то нужно добавить в модели, описывающие сущности содержания связь с моделью `User` через ключ `user_id`
3. Не нашел инфы о поддерживаемых локалях.

Остальное все понятно написано.

Что заметил насчет оформления:
1) Ссылки Why? в https://github.com/TheRole/docs/blob/master/Limitations.md битые
2) [ Back to TheRole ] во всех доках ссылается на https://github.com/the-teacher/the_role

И еще из чтения документации пришли идеи дальнейшего развития проекта. Можно добавить такие фичи:
- наследование ролей: предположим есть роль User (чтение), Autor(создание), Redacor(изменение), Moderator(изменение видимости публикации), Admin. Из этого выходит что в json представлении можно Redactor задать так `{"base_role":"Autor","pwermissions":{"articles":{"update":true}}`. Теперь редактор имеет теже права что и Autor + право на обновление статей. Это будет удобнее в том случае когда секций и прав много. Проще будет разобраться с наследованием чем со строкой в 500 символов.
- Настройка куда монтировать Managment Panel. Это мне кажется более гибко, чем добавление примисей в роуты. Потому что путь к админке может различаться. Я так понимаю это можно релизовать через `mount TheRoleManagementPanel, at: '/admin'`
- Предоставлять возможеость Managment Panel
- Убрать генераторы из Managment Panel. В них теперь нет необходимости.

**Comment by the-teacher** [comment]
Hello!

I glad to inform - TheRole 3.0 released.
Few bugs was fixed and code of gem was reworked.

We will be happy to get any feedback from users of TheRole to build new Road Map for gem.

Thank you for your participation!
